spring:
  application:
    name: KafkaProducer
  profiles:
    active: local
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9093,127.0.0.1:9094,127.0.0.1:9095
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
    port: 9012